import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./Components/Header";
import PersonalCard from "./Components/PersonalCard";
import Tools from "./Components/Tools";
import Experience from "./Components/Experience";
import BottomNav from "./Components/BottomNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <head>
        <title>Aneesh's Portfolio</title>
      </head>
      <body>
       
        <div className="landing">
        <PersonalCard />
        <Tools />
        </div>
        
        <Experience />
        <BottomNav />
        
      </body>
    </html>
  );
}
